### ISSUE TITLE
[maimai/fetch-internal-levels] SQLite NOT NULL Constraint

### ISSUE THREAD

**Issue by DadangSudadang** [zetaraku/arcade-songs-fetch#6]
```
> arcade-songs-fetch@0.0.0 maimai:fetch-internal-levels
> ts-node src/maimai/fetch-internal-levels

[2024-02-29T18:09:26.734] [INFO] maimai/fetch-internal-levels - Fetching data from internal level source ...
[2024-02-29T18:09:28.394] [INFO] maimai/fetch-internal-levels - Reading data from BUDDiES新曲 at column 0,6,12,18,24 ...
[2024-02-29T18:09:29.995] [INFO] maimai/fetch-internal-levels - Reading data from 14以上 at column 0,7,14,21,28,35 ...
[2024-02-29T18:09:31.479] [INFO] maimai/fetch-internal-levels - Reading data from 13+ at column 0,7,14,21 ...
[2024-02-29T18:09:33.624] [INFO] maimai/fetch-internal-levels - Reading data from 13 at column 0,7,14,21,28,35,42 ...
[2024-02-29T18:09:35.049] [INFO] maimai/fetch-internal-levels - Reading data from 12+ at column 0,6,12,19,26,33 ...
[2024-02-29T18:09:36.638] [INFO] maimai/fetch-internal-levels - Reading data from 12+ at column 39 ...
[2024-02-29T18:09:38.078] [INFO] maimai/fetch-internal-levels - Reading data from 12 at column 0,6,13,19,26,32 ...
[2024-02-29T18:09:39.376] [INFO] maimai/fetch-internal-levels - Reading data from 12 at column 38 ...
[2024-02-29T18:09:44.250] [INFO] maimai/fetch-internal-levels - Reading data from Tmai at column 0 ...
[2024-02-29T18:09:44.271] [INFO] maimai/fetch-internal-levels - OK, 1402 sheets fetched.
[2024-02-29T18:09:44.271] [INFO] maimai/fetch-internal-levels - Updating sheetInternalLevels ...
[parent_directory]/arcade-songs-fetch/node_modules/sequelize/src/dialects/sqlite/query.js:236
      const errForStack = new Error();
                          ^
Error
    at Database.<anonymous> ([parent_directory]/arcade-songs-fetch/node_modules/sequelize/src/dialects/sqlite/query.js:236:27)
    at [parent_directory]/arcade-songs-fetch/node_modules/sequelize/src/dialects/sqlite/query.js:234:50
    at new Promise (<anonymous>)
    at Query.run ([parent_directory]/arcade-songs-fetch/node_modules/sequelize/src/dialects/sqlite/query.js:234:12)
    at [parent_directory]/arcade-songs-fetch/node_modules/sequelize/src/sequelize.js:650:28
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SQLiteQueryInterface.upsert ([parent_directory]/arcade-songs-fetch/node_modules/sequelize/src/dialects/abstract/query-interface.js:853:12)
    at async Function.upsert ([parent_directory]/arcade-songs-fetch/node_modules/sequelize/src/model.js:2606:20)
    at async Promise.all (index 735)
    at async run ([parent_directory]/arcade-songs-fetch/src/maimai/fetch-internal-levels.ts:369:3) {
  name: 'SequelizeUniqueConstraintError',
  errors: [],
  parent: [Error: SQLITE_CONSTRAINT: NOT NULL constraint failed: SheetInternalLevels.type] {
    errno: 19,
    code: 'SQLITE_CONSTRAINT',
    sql: 'INSERT INTO `SheetInternalLevels` (`songId`,`type`,`difficulty`,`internalLevel`) VALUES ($1,$2,$3,$4) ON CONFLICT (`songId`,`type`,`difficulty`) DO UPDATE SET `songId`=EXCLUDED.`songId`,`difficulty`=EXCLUDED.`difficulty`,`internalLevel`=EXCLUDED.`internalLevel`;'
  },
  original: [Error: SQLITE_CONSTRAINT: NOT NULL constraint failed: SheetInternalLevels.type] {
    errno: 19,
    code: 'SQLITE_CONSTRAINT',
    sql: 'INSERT INTO `SheetInternalLevels` (`songId`,`type`,`difficulty`,`internalLevel`) VALUES ($1,$2,$3,$4) ON CONFLICT (`songId`,`type`,`difficulty`) DO UPDATE SET `songId`=EXCLUDED.`songId`,`difficulty`=EXCLUDED.`difficulty`,`internalLevel`=EXCLUDED.`internalLevel`;'
  },
  fields: [],
  sql: 'INSERT INTO `SheetInternalLevels` (`songId`,`type`,`difficulty`,`internalLevel`) VALUES ($1,$2,$3,$4) ON CONFLICT (`songId`,`type`,`difficulty`) DO UPDATE SET `songId`=EXCLUDED.`songId`,`difficulty`=EXCLUDED.`difficulty`,`internalLevel`=EXCLUDED.`internalLevel`;'
}
```

Happens after today's update (Tsunagite, Chunithm Chiho and Utage update). There could be something wrong in the CC spreadsheet, I think.

**Comment by zetaraku** [comment]
Ah, a sneaky malformed record...

![Screenshot 2024-02-29 at 19-58-52 mDX9 0 BUDDiES譜面定数表](https://github.com/zetaraku/arcade-songs-fetch/assets/9212875/0b66ac39-96fa-410e-a10c-1d105893a3b7)

Reported to the spreadsheet maintainer :)

**Comment by DadangSudadang** [comment]
Thank you!

**Comment by zetaraku** [comment]
They fixed the spreadsheet :)

**Comment by DadangSudadang** [comment]
Thanks, I can confirm it works fine now.
