### ISSUE TITLE
sqlite/query.js: SQLITE_ERROR: no such column: comment

### ISSUE THREAD

**Issue by DadangSudadang** [zetaraku/arcade-songs-fetch#7]
Happens when running maimai fetch-songs, fetch-images and fetch-internal-levels.

```
> arcade-songs-fetch@0.0.0 maimai:fetch-songs
> ts-node src/maimai/fetch-songs

[2024-05-30T19:18:19.895] [INFO] maimai/fetch-songs - Fetching data from: https://maimai.sega.jp/data/maimai_songs.json ...
[2024-05-30T19:18:20.179] [INFO] maimai/fetch-songs - OK, 1244 songs fetched.
[2024-05-30T19:18:20.180] [INFO] maimai/fetch-songs - Ensuring every song has an unique songId ...
[2024-05-30T19:18:20.240] [INFO] maimai/fetch-songs - Updating songs ...
[parent_dir]/arcade-songs-fetch/node_modules/sequelize/src/dialects/sqlite/query.js:236
      const errForStack = new Error();
                          ^
Error
    at Database.<anonymous> ([parent_dir]/arcade-songs-fetch/node_modules/sequelize/src/dialects/sqlite/query.js:236:27)
    at /home/dadangsu/ドキュメント/Other-projects/maimai-visualizer-project/scores_per_version_html/arcade-songs-fetch/node_modules/sequelize/src/dialects/sqlite/query.js:234:50
    at new Promise (<anonymous>)
    at Query.run ([parent_dir]/arcade-songs-fetch/node_modules/sequelize/src/dialects/sqlite/query.js:234:12)
    at [parent_dir]/arcade-songs-fetch/node_modules/sequelize/src/sequelize.js:650:28
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SQLiteQueryInterface.upsert ([parent_dir]/arcade-songs-fetch/node_modules/sequelize/src/dialects/abstract/query-interface.js:853:12)
    at async Function.upsert ([parent_dir]/arcade-songs-fetch/node_modules/sequelize/src/model.js:2606:20)
    at async Promise.all (index 1206)
    at async run ([parent_dir]/arcade-songs-fetch/src/maimai/fetch-songs.ts:127:3) {
  name: 'SequelizeDatabaseError',
  parent: [Error: SQLITE_ERROR: table Songs has no column named comment] {
    errno: 1,
    code: 'SQLITE_ERROR',
    sql: 'INSERT INTO `Songs` (`songId`,`category`,`title`,`artist`,`imageName`,`imageUrl`,`version`,`releaseDate`,`isNew`,`isLocked`,`comment`) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT (`songId`) DO UPDATE SET `songId`=EXCLUDED.`songId`,`category`=EXCLUDED.`category`,`title`=EXCLUDED.`title`,`artist`=EXCLUDED.`artist`,`imageName`=EXCLUDED.`imageName`,`imageUrl`=EXCLUDED.`imageUrl`,`version`=EXCLUDED.`version`,`releaseDate`=EXCLUDED.`releaseDate`,`isNew`=EXCLUDED.`isNew`,`isLocked`=EXCLUDED.`isLocked`,`comment`=EXCLUDED.`comment`;'
  },
  original: [Error: SQLITE_ERROR: table Songs has no column named comment] {
    errno: 1,
    code: 'SQLITE_ERROR',
    sql: 'INSERT INTO `Songs` (`songId`,`category`,`title`,`artist`,`imageName`,`imageUrl`,`version`,`releaseDate`,`isNew`,`isLocked`,`comment`) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT (`songId`) DO UPDATE SET `songId`=EXCLUDED.`songId`,`category`=EXCLUDED.`category`,`title`=EXCLUDED.`title`,`artist`=EXCLUDED.`artist`,`imageName`=EXCLUDED.`imageName`,`imageUrl`=EXCLUDED.`imageUrl`,`version`=EXCLUDED.`version`,`releaseDate`=EXCLUDED.`releaseDate`,`isNew`=EXCLUDED.`isNew`,`isLocked`=EXCLUDED.`isLocked`,`comment`=EXCLUDED.`comment`;'
  },
  sql: 'INSERT INTO `Songs` (`songId`,`category`,`title`,`artist`,`imageName`,`imageUrl`,`version`,`releaseDate`,`isNew`,`isLocked`,`comment`) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT (`songId`) DO UPDATE SET `songId`=EXCLUDED.`songId`,`category`=EXCLUDED.`category`,`title`=EXCLUDED.`title`,`artist`=EXCLUDED.`artist`,`imageName`=EXCLUDED.`imageName`,`imageUrl`=EXCLUDED.`imageUrl`,`version`=EXCLUDED.`version`,`releaseDate`=EXCLUDED.`releaseDate`,`isNew`=EXCLUDED.`isNew`,`isLocked`=EXCLUDED.`isLocked`,`comment`=EXCLUDED.`comment`;',
  parameters: {}
}
```

**Comment by zetaraku** [comment]
Remember to run `npm run db:migrate:all` as the schema has changed :)

**Comment by DadangSudadang** [comment]
Oops my bad. Should've read the readme again lol. Thanks.
